const interactionsType = {
    BUTTON_CLICK: 'button_click',
    PAGE_LOAD: 'page_load',
    FORM_SUBMISSION: 'form_submission',
    LINK_CLICK: 'link_click',
    VIDEO_PLAY: 'video_play',
    AUDIO_PLAY: 'audio_play',
    FILE_UPLOAD: 'file_upload',
    SEARCH: 'search',
    MENU_NAVIGATION: 'menu_navigation',
    ITEM_SELECTION: 'item_selection',
    CHAT_MESSAGE: 'chat_message',
    EMAIL_SENT: 'email_sent',
    LOGOUT: 'logout',
    LOGIN: 'login',
    SIGNUP: 'signup',
    PROFILE_UPDATE: 'profile_update',
    PASSWORD_CHANGE: 'password_change',
    NOTIFICATION_READ: 'notification_read',
    NOTIFICATION_CLICK: 'notification_click',
    ERROR_OCCURRED: 'error_occurred',
    PAGE_NOT_FOUND: 'page_not_found',
    DATA_EXPORT: 'data_export',
    DATA_IMPORT: 'data_import',
    PAYMENT_PROCESS: 'payment_process',
    ACCOUNT_DELETE: 'account_delete',
    COOKIE_CONSENT: 'cookie_consent',
    SURVEY_RESPONSE: 'survey_response',
  };
  
  module.exports = interactionsType;
  